# Generated by Django 3.2.8 on 2021-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pretest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=25)),
                ('question', models.CharField(blank=True, max_length=25)),
                ('choice', models.CharField(max_length=25)),
                ('instructionTime', models.CharField(blank=True, max_length=25)),
                ('quiz1Time', models.CharField(blank=True, max_length=25)),
                ('quiz2Time', models.CharField(blank=True, max_length=25)),
                ('feedbackTime', models.CharField(blank=True, max_length=25)),
                ('duration', models.CharField(blank=True, max_length=25)),
                ('numClicks', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='pretestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=25)),
                ('user', models.CharField(blank=True, max_length=25)),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=100)),
                ('timeStamp', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=25)),
                ('question', models.CharField(blank=True, max_length=25)),
                ('choice', models.CharField(max_length=25)),
                ('instructionTime', models.CharField(blank=True, max_length=25)),
                ('quiz1Time', models.CharField(blank=True, max_length=25)),
                ('quiz2Time', models.CharField(blank=True, max_length=25)),
                ('feedbackTime', models.CharField(blank=True, max_length=25)),
                ('duration', models.CharField(blank=True, max_length=25)),
                ('numClicks', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='vectorsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=25)),
                ('user', models.CharField(blank=True, max_length=25)),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
    ]
