# Generated by Django 3.2.8 on 2021-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_LLG', '0002_vectorsmouseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='clickX',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='clickY',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='clickedITMbr',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='clickedITMtl',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='mouseX',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='mouseY',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
