# Generated by Django 3.2.8 on 2021-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_LLG', '0003_auto_20211209_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsmouseevent',
            name='event',
            field=models.CharField(max_length=100),
        ),
    ]
