# Generated by Django 3.2.8 on 2021-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_LLG', '0006_auto_20211215_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestlog',
            name='clickX',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pretestlog',
            name='clickY',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorslog',
            name='clickX',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorslog',
            name='clickY',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
